version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  sniffer:
    build: .
    container_name: packet_sniffer
    depends_on:
      - mongo
    network_mode: "host"
    volumes:
      - .:/app
